services:
  web:
    restart: unless-stopped

  app:
    restart: unless-stopped

  db:
    restart: unless-stopped
    app:
        ports: []

    db:
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
