services:
  app:
    ports: []
    volumes:
      - ./.env:/var/www/.env:ro
      - public_storage:/var/www/storage/app/public

  web:
    volumes:
      - public_storage:/var/www/public/storage:ro

volumes:
  public_storage:
